### ISSUE TITLE
Missing * in Objective C array properties

### ISSUE THREAD

**Issue by Andr3s4n** [tomasz-m/realmGenerator#3]
In this method:
`function getFieldsObjectiveC($values) { }`

This line: `$type = "RLMArray<" . $param . " *><" . $param . "> ";`
Should end like this: `$type = "RLMArray<" . $param . " *><" . $param . "> *";`

Example:
`@property RLMArray<Client *><Client> *clients;`

Object pointers should start with `*`.

**Comment by tomasz-m** [comment]
Thanks for the report and sorry for my big delay:)
Fixed and available on realmgenerator.eu
